# Chart tá»« Bitnami Redis
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: redis
  repo: oci://registry-1.docker.io/bitnamicharts
  releaseName: redis
  namespace: redis
  version: 19.0.2
  valuesFile: values.yaml
