apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-workloads
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Hoangvu75/k8s_manifest.git
        revision: master
        directories:
          - path: "k8s_manifest/*/*"
            exclude: false
  
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        namespace: '{{path[1]}}'
        workload: '{{path.basename}}'
        managed-by: applicationset
    
    spec:
      project: default
      
      source:
        repoURL: https://github.com/Hoangvu75/k8s_manifest.git
        targetRevision: master
        path: '{{path}}'
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
---
# Application cho cả Projects và Namespaces (sync waves sẽ đảm bảo thứ tự)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-bootstrap
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Hoangvu75/k8s_manifest.git
    targetRevision: master
    path: k8s_manifest
    directory:
      recurse: false
      include: '{projects,namespaces}.yaml'  # Include cả 2 files
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
