version: '3'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    privileged: true
    ports:
      - "8081:443"
    volumes:
      - rancher-data:/var/lib/rancher
      - rancher-log:/var/log/auditlog
    environment:
      CATTLE_TELEMETRY_OPT: out
    networks:
    - rancher-net
networks:
  rancher-net:
    driver: bridge
volumes:
  rancher-data:
    driver: local
  rancher-log:
    driver: local