apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Grafana — chart chính thức
# Repo: https://grafana.github.io/helm-charts

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesFile: values.yaml

