apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Rancher Server — Helm chart chính thức
# Repo: https://releases.rancher.com/server-charts/latest

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    releaseName: rancher
    namespace: cattle-system
    valuesFile: values.yaml

