apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm chart Rancher chính thức
# Repo docs: https://ranchermanager.docs.rancher.com/

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    releaseName: rancher
    namespace: cattle-system
    valuesFile: values.yaml

