apiVersion: v2
name: standalone-app
description: Generic helm chart for standalone applications

type: application

version: 1.1.0

keywords:
  - java
  - node
  - dotnet
  - kubernetes
  - application

home: ""
maintainers: []
