# Chart từ Docker Hub OCI: hoangvu753/standalone-app (giống jenkins, n8n)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: standalone-app
  repo: oci://registry-1.docker.io/hoangvu753
  releaseName: sample-gitops-web
  namespace: sample-gitops-web
  version: 1.1.0
  valuresources:
  - rbac.yaml
  - values.yaml
