apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-gitops-web-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-gitops-web-admin-binding
subjects:
  - kind: ServiceAccount
    name: sample-gitops-web
    namespace: sample-gitops-web
roleRef:
  kind: ClusterRole
  name: sample-gitops-web-admin
  apiGroup: rbac.authorization.k8s.io
