# Chart chính thức: https://helm.goharbor.io
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: harbor
  repo: https://helm.goharbor.io
  releaseName: harbor
  namespace: harbor
  version: "1.14.0"
  valuesFile: values.yaml
