apiVersion: v1
kind: Pod
metadata:
  name: helm-installer
  namespace: default
spec:
  serviceAccountName: helm-admin
  containers:
    - name: helm
      image: alpine/helm:latest
      # Giữ container chạy liên tục để ta exec vào
      command: ["/bin/sh", "-c", "sleep 36000"]

