apiVersion: v1
kind: Pod
metadata:
  name: helm-installer
  namespace: default
spec:
  serviceAccountName: helm-admin
  containers:
    - name: helm
      # Image này có sẵn: kubectl, helm, và các tool k8s khác
      image: alpine/k8s:1.28.3
      # Giữ container chạy liên tục để ta exec vào
      command: ["/bin/sh", "-c", "sleep 36000"]

