# Chart tá»« Docker Hub OCI: hoangvu753/standalone-app
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: helm-application
  repo: oci://registry-1.docker.io/hoangvu753
  releaseName: n8n
  namespace: n8n
  version: 6.16.1
  valuesFile: values.yaml
  additionalValuesFiles:
    - values-secret.yaml
