# Metadata cho Argo CD
# appName: mbs-discord-bot
# destNamespace: mbs-discord-bot

# ArgoCD Notifications
annotations:
  notifications.argoproj.io/subscribe.on-sync-succeeded.n8n: ""
  notifications.argoproj.io/subscribe.on-sync-failed.n8n: ""
  notifications.argoproj.io/subscribe.on-deployed.n8n: ""
