# Chart tá»« Docker Hub OCI: hoangvu753/standalone-app
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml

helmCharts:
- name: helm-application
  repo: oci://registry-1.docker.io/hoangvu753
  releaseName: cloudflared
  namespace: cloudflared
  version: 6.16.1
  valuesFile: values.yaml
