---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgA5mtcw5TRnAbpVzcFZNMaECnqvh/3YM7cqWAyZQi0IfWuXiL5rg0aYPhk5/aKdmFNcD1nKk4gf6eetVxFLVCKwvP5I7i3+CNQsFds/ZnYhlomyRBxXDRN0F1gacd+Nqlb3eIS0/irELb6oXYkOaMrTAa5ic1ku90HPovkvgiSv0sn2lwUfu7tPaUXMX5L7890DCACHsUQC2fKpOsg2H1N9O2upIaiy68QzOWZwza67CiFxZZ9FfsZUFSCFM9Tg/7iHX4CKr6fsZVgF/C/nQZMcHW352XoKE4TmJ5WYFv/Ck6bQKZY7eZ7ckMqaJw/suNM0dQAUeZtfxmx0lM7t9BpzgmXPoNN4GFLeqkwqz9xXup0djP0YCr5jixYXU/6Sgi+M4xtBwbpXffaahY+S8VzEAowcDdRgO33pZ84GX3ttKu1eq8x2JlyTCRNqvzFvRY1rSURmy+m+3+1oZTRXeEn+RJDddH5bB9QJoIBjxjRzPpmcG9lO22eQjmClkE8p6ZHBg80vyv2qZtLBEO+G9rUXy5CmQrClPKpzVleH48fsoyInNYTpGA5RmO2D+atmXXfsqO5Zq0HofVx8u1dnbe7L8Ja1mzrftN1AsZX4jyUG7fTb+ro2XDwrDh+0XOCL/rQGtvXEhCuvoreVGIUMIsq7tDPXVBooGNc8bFScGQcQdjNvJPe+gdKMifBCHKqxpEUPegfMfYTe4AdrjRxVMZOosiP9zAaHgcx/v0h9yJDqyc8xiMKZpzRoKSnETqCbVSUwaLpoDsGEF6hfNmkQ5fyg7iofnhWGuQlOmpmA3dBs+0innSp0q5VzaWJibvK5jrniI/0zXWKrkFj02khV5qCdZ4zkRzH1EjzViyBNiVUMHy7pM9V0wf4suNSodKqGUjSeU5td0QRn0JHmDgbpSPw8pzvJcvQKA5vFwlSEsNrT86R/4NoDIXmY
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
    type: Opaque
