---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBEKu78QigzE9MeW4i+Y+zy3V6B+3LoEZROarg2eTFWsp9yzL8HhT37054JJO7mUkvLb9OU9m1DIFcxcY6FW6DCeglfkFOhVO+aaXwftaGmKtJS65EIkqADYxCq2tHZYYOS6SygElTBgcR8YjIc2hBmF/Zh2oI7/47cbqraE/PR7rV5hNsB6mtzIJKyCVRc34UXoWS3jW0YYRIv3GYdE/rwXXef3dEpMWEj6JiKlnY8XOt/HfKPPe8Ty1s62XnOYrMCim//HOxQRy3FQ8MUEV0FAwYAFJlnZFfFM1f5ljo22DpZNjQ6qlPxZR3vI+B9LtNt1kRcruyO9hQwnaLWpXbiShxp9WdqUhgL6Rg/gARBbpWOQsDzERb7KI+e3sWM4U/HCZ4TUNtwGXW+9ASoQwB7xEkvDCguYEIIoeQtjrsdlXxNVIE7NHXu1ZAmlJd+IO8xMLFej1bfwNJTjhMTnTX+X/DNS8O0k8xR1QMN84b/ZXYCYMQQXJg/D31siquOjiUH+aOA7q8jZZmWyIq2nNNLhtQpHJAws/FpJKDpseRMXdr0asXo5mQBNqVdSBCWatEiMKwfrFNaKdTjkMnUW0o7yI1vN372lGwsNJczCFBGhKOqfyDk7vaY4zAf62ofhmbjMIlbK3PCXIjzbmvCAnlJfxfhv7Cncs8gpgO/JBx5NvM75bQKhqHr1QtA6IX2+R3LY+G7dQQe1Hf7BNYJJFxKvNzBEJ0EulDACecuX3jaEPHLy28O2pyzTUTYai1QDzHcaDeqrmhkHcbpuVboUtmCiK8TC33lsXtB/fHUFC0E3kijXKVeuHoVY5Wm7A8u31wELufonR4PvEQg7p2CKFukw51CEDyH8HCQ5sMi+LINZ4OfgzWe7/m6ds5U38qt3h7Y9CBtBS/Yvc/3ShvzkYdGeIlg/kgSHuffsG48/+Q0t1MaSdt8FYQk
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
    type: Opaque
