apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-scan-cluster-reader
  labels:
    app.kubernetes.io/name: trivy-scan
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["list", "get", "create", "delete", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["list", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "get", "create", "delete", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["list", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["list", "get"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["list", "get"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["list", "get"]
