apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml

helmCharts:
- name: helm-application
  repo: oci://registry-1.docker.io/hoangvu753
  releaseName: trivy-scan
  namespace: trivy-scan
  version: 6.16.1
  valuesFile: values.yaml
