# Metadata cho Argo CD (optional)
# appName: sample-gitops-web
# destNamespace: sample-gitops-web
# repoURL: https://github.com/Hoangvu75/k8s_manifest.git
# srcPath: apps/playground/sample-gitops-web
