# Chart tá»« Docker Hub OCI: hoangvu753/standalone-app + ServiceAccount cho K8s plugin
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jenkins-sa.yaml

helmCharts:
- name: helm-application
  repo: oci://registry-1.docker.io/hoangvu753
  releaseName: jenkins
  namespace: jenkins
  version: 6.16.1
  valuesFile: values.yaml
  additionalValuesFiles:
    - values-secret.yaml
