# Giống công ty: 1 chart chung (charts/standalone-app), app chỉ có values
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: standalone-app
    repo: file://../../../../charts/standalone-app
    releaseName: jenkins
    namespace: jenkins
    version: "1.1.0"
    valuesFile: values.yaml
    additionalValuesFiles:
      - values-secret.yaml
